name: Android Test




on:

  push:
    branches:
      - 'release'

  jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    -name: Checkout code
      - uses: actions/checkout@v3
      - name: Set up Android
        uses: actions/ setup-android@v1
      - name: Run unit tests
        run: ./gradlew test
      - name: Run UI tests
        run: echo ./gradlew connectedAndroidTest
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
         name: test-results
         path: ./app/bulid/reports

      
